name = "warp-generator"
compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat"]

main = "worker.js"

[site]
bucket = "./out"

[vars]
NODE_ENV = "production"

[observability.logs]
enabled = true