name = "WarpGenerator"
compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install --legacy-peer-deps && npm run build"

[observability.logs]
enabled = true

[vars]
NODE_ENV = "production"